language: emacs-lisp
sudo: false
cache:
- directories:
  - "$HOME/emacs"
env:
  global:
  - EMAKE_SHA1=4026405ca5ba93a739e33c2a3e46f796a7661635
  - EMACS_DIR=$HOME/emacs
  - EMACS=$HOME/emacs/src/emacs
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
  - make setup
install:
  - make install
script:
  - make test         # test uncompiled
  - make compile
  - make test         # test compiled
