language: generic
sudo: false
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
env:
  global:
  - EMAKE_SHA1=d8ab7790f5823547fd4e7aec2218771a3dda0638
  - EMACS_DIR=$HOME/emacs
  - EMACS=$HOME/emacs/src/emacs
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
  - make setup
install:
  - make install
script:
  - make test         # test uncompiled
  - make compile-noerr
  - make test         # test compiled
